# golangci-lint v2 requires version to be specified
version: 2

run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    # - depguard  # TODO: Fix v2 configuration - currently blocking all imports
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - mnd
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell    # auto-fix: spelling errors
    - nakedret
    - noctx
    - nolintlint  # auto-fix: nolint directives
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace  # auto-fix: unnecessary newlines
    - godot       # auto-fix: comments should end with period
    - usestdlibvars  # auto-fix: use stdlib constants

  disable:
    - gochecknoglobals
    - godox
    - godot
    - err113
    - wsl
    - nlreturn
    - testpackage

linters-settings:
  depguard:
    rules:
      Main:
        list-mode: lax
        files:
          - $all
        allow:
          - $gostd  # Go standard library
          - github.com/rizome-dev/opun  # Allow all project imports
          - github.com  # Allow all github imports except explicitly denied
          - gopkg.in  # Allow gopkg.in imports (e.g., yaml.v3)
          - golang.org  # Allow golang.org imports (e.g., x/term)
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "Use standard library errors package with fmt.Errorf"
  
  dupl:
    threshold: 100
  
  funlen:
    lines: 100
    statements: 50
  
  goconst:
    min-len: 2
    min-occurrences: 2
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  gocyclo:
    min-complexity: 15
  
  
  mnd:
    checks:
      - argument
      - case
      - condition
      - return
  
  lll:
    line-length: 140
  
  misspell:
    locale: US
  
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
  
  revive:
    confidence: 0

issues:
  exclude-rules:
    # Skip test files entirely
    - path: "_test\\.go"
      linters:
        - all
    
    # Skip _archive directory
    - path: "^_archive/"
      linters:
        - all
    
    # Skip vendor directory
    - path: "^vendor/"
      linters:
        - all
    
    # Exclude some linters from running on CLI files
    - path: internal/cli/
      linters:
        - dupl
        - funlen
    
    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "
    
    # Allow G204 in specific cases for subprocess execution
    - path: internal/mcp/tool_executor.go
      linters:
        - gosec
      text: "G204"
    
    - path: internal/providers/
      linters:
        - gosec
      text: "G204"
    
    - path: internal/pty/
      linters:
        - gosec
      text: "G204"

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
  
  # Show only new issues created after git revision
  new: false