name: Nightly Release

on:
  push:
    tags:
      - 'v*-nightly'  # Matches v1.0.0-nightly, v2.0.0-nightly, etc.

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  deploy-nightly:
    name: Deploy to opun-nightly
    runs-on: ubuntu-latest
    env:
      HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Validate nightly tag
      run: |
        TAG="${{ github.ref_name }}"
        if [[ ! "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-nightly$ ]]; then
          echo "Not a nightly tag, skipping..."
          exit 1
        fi
        echo "Detected nightly tag: $TAG"

    - name: Run GoReleaser for Nightly
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --clean --config .goreleaser.nightly.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}